### PR TITLE
SOL-55618: remove non-GA feature samples

### PR DESCRIPTION
**Pull request by aaron-613**
Temporarily removing the samples as the features are not GA yet:

- HowToUseCachedMessageSubscriptions.java
- HowToUseLocalTransactions.java
- HowToUseRequestReplyPattern.java

### CODE REVIEW

**Comment by TamimiGitHub** [comment]
LGTM! We can merge when we remove the references to these files from https://github.com/SolaceDev/solace-dev-tutorials/blob/master/src/pages/tutorials/java/_howtos.yml

**Comment by Mrc0113** [comment]
Note: yes we can remove the code in the `main` branch, but I just want to make sure the code isn't lost and it's in some other branch to be easily re-used when those features are added. Is that part of this or has that already been done?

**Comment by aaron-613** [comment]
Sorry!  I should have mentioned:
 - those 3 samples have been backed up, and are also still available in SolaceDev original GH repo
 - the tutorials listing has been updated to, those 3 removed: https://github.com/SolaceDev/solace-dev-tutorials/commit/1c3ee7dd9222c5113b69a24f8899a45300acea1d#diff-bd4db656e4190a8bcdd90b62897e97d3304b3c5ba511b29bd4c62cbd33351f35

**Comment by Mrc0113** [comment]
Thanks Aaron, merging 👍

**Pull request merged**
