### PR TITLE
Added Partitioned Queue Snippets

### PR DESCRIPTION
**Pull request by mayur-solace**

### CODE REVIEW

**Comment by HookWoods** [comment]
Hello, nice PR, will this also contain the part for the subscription part? Ty!

**Comment by mayur-solace** [comment]
> Hello, nice PR, will this also contain the part for the subscription part? Ty!

No change required on the consumer/receiver part ☺️, continue to use the PersistentMessageReceiver as you are using currently.
A complete example should follow under /com/solace/samples/java/patterns when Partition Queue feature in this Java API is near to GA.

**Comment by Mrc0113** [comment]
@mayur-solace should this still be in draft state?

**Comment by mayur-solace** [comment]
> @mayur-solace should this still be in draft state?

@Mrc0113 It can be merged. I just updated the solace-messaging-client to latest 1.4.0.

**Pull request merged**
